# Generated by Django 5.1.1 on 2025-10-21 05:31

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_case_caseattachment_prescription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='medical_history',
        ),
        migrations.AddField(
            model_name='case',
            name='symptoms',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_number',
            field=models.CharField(default=core.models.generate_case_number, editable=False, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
