# Generated by Django 5.1.1 on 2025-10-21 07:00

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='prescription_number',
            field=models.CharField(default=core.models.generate_prescription_number, editable=False, max_length=64, unique=True),
        ),
    ]
